apiVersion: v1
kind: Pod
metadata:
  name: postgres-client
spec:
  containers:
  - name: postgres-client
    image: postgres:latest
    command: ["bash", "-c"]
    args:
    - |
      apt-get update && apt-get install -y postgresql-client
      PGPASSWORD=$POSTGRES_PASSWORD psql -h $POSTGRES_HOST -U $POSTGRES_USER -d $POSTGRES_DB
      while true; do sleep 86400; done
    env:
    - name: POSTGRES_HOST
      value: postgres.default.svc.cluster.local 
    - name: POSTGRES_USER
      valueFrom:
        secretKeyRef:
          name: db-user-pass
          key: username
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-user-pass
          key: password
    - name: POSTGRES_DB
      value: golyrid

